[package]
name = "pi_base58"
version = "0.1.0"
authors = ["moyy <moyy@gmail.com>"]
edition = "2021"
description = "base58 encoding & decoding."
repository = "https://github.com/GaiaWorld/pi_base58"
license = "MIT OR Apache-2.0"
keywords = ["pi", "base58"]

[dependencies]